regions:
    post:
        url: /Comment/api/form/FooComment-Post
        partial: Comment/forms/post.hbs
        type: Form
    comments:
        url: /Comment/api/collection/comments
        partial: Comment/collections/comments.hbs
        type: Collection